- name: create user xsnippet
  user:
    name: xsnippet
    createhome: yes
  become: true
  become_user: root

- name: allow xsnippet's systemd units to start w/o an explicit login session
  command: "loginctl enable-linger xsnippet"
  args:
    creates: "/var/lib/systemd/linger/xsnippet"
  become: true
  become_user: root

- name: create and mount the external volume for storing xsnippet-db's data (if it is configured)
  include_role:
    name: volume
    apply:
      become: yes
      become_user: root
  vars:
    external_volume: "{{ xsnippet_db_external_volume }}"
  when: xsnippet_db_external_volume

- file:
    path: "/home/xsnippet/xsnippet-web"
    state: directory
- file:
    path: "/home/xsnippet/data/db"
    state: directory
- file:
    path: "/home/xsnippet/nginx-conf.d"
    state: directory
- file:
    path: "/home/xsnippet/.config/systemd/user"
    state: directory
- file:
    path: "/home/xsnippet/.config/letsencrypt"
    state: directory
  when: xsnippet_api_https_enabled or xsnippet_spa_https_enabled

- name: prepare the certbot config
  template:
    src:  certbot.ini.j2
    dest: "/home/xsnippet/.config/letsencrypt/cli.ini"
    mode: 0600
    owner: xsnippet
    group: xsnippet
  when: xsnippet_api_https_enabled or xsnippet_spa_https_enabled

- name: prepare the certbot-dns-digitalocean config
  template:
    src:  dns-digitalocean-credentials.ini.j2
    dest: "/home/xsnippet/.config/letsencrypt/dns-digitalocean-credentials.ini"
    mode: 0600
    owner: xsnippet
    group: xsnippet
  when: xsnippet_api_https_enabled or xsnippet_spa_https_enabled

- name: generate ssl for {{ xsnippet_api_server_name }}
  command: certbot certonly --domains {{ xsnippet_api_server_name }}
  args:
    creates: "/home/xsnippet/.config/letsencrypt/live/{{ xsnippet_api_server_name }}/*.pem"
  when: xsnippet_api_https_enabled

- name: generate ssl for {{ xsnippet_spa_server_name }}
  command: certbot certonly --domains {{ xsnippet_spa_server_name }}
  args:
    creates: "/home/xsnippet/.config/letsencrypt/live/{{ xsnippet_spa_server_name }}/*.pem"
  when: xsnippet_spa_https_enabled

- name: prepare the certbot systemd units
  copy:
    src: "{{ item }}"
    dest: "/home/xsnippet/.config/systemd/user/"
    remote_src: yes
  loop:
    - /lib/systemd/system/certbot.service
    - /lib/systemd/system/certbot.timer

- name: enable the certbot renew periodic timer
  systemd:
    name: certbot.timer
    enabled: yes
    state: restarted
    scope: user

# Due to the issue [1], we cannot use 'unarchive' module to download and
# extract the archive while under 'become_user' mode; there's something
# increadibly wrong about tmpdir manipulating. Therefore, we do two-step
# action: first, download the archive; second, extract it to the target
# directory.
#
# [1]: https://github.com/ansible/ansible/issues/38672
- name: prepare xsnippet-web assets
  get_url:
    url: "{{ xsnippet_web_assets }}"
    dest: /tmp/xsnippet-web.tar-gz
    force: true
- unarchive:
    src: /tmp/xsnippet-web.tar-gz
    dest: "/home/xsnippet/xsnippet-web"
    remote_src: yes

- name: prepare the webserver config for API
  template:
    src:  xsnippet-webserver-api.conf.j2
    dest: "/home/xsnippet/nginx-conf.d/xsnippet-webserver-api.conf"
    mode: 0600
    owner: xsnippet
    group: xsnippet
- name: prepare the webserver config for SPA
  template:
    src:  xsnippet-webserver-spa.conf.j2
    dest: "/home/xsnippet/nginx-conf.d/xsnippet-webserver-spa.conf"
    mode: 0600
    owner: xsnippet
    group: xsnippet
- template:
    src: conf.json.j2
    dest: "/home/xsnippet/xsnippet-web/conf.json"
    mode: 0644
    owner: xsnippet
    group: xsnippet
- name: prepare the webserver JS handlers
  template:
    src: xsnippet_api.js.j2
    dest: "/home/xsnippet/nginx-conf.d/xsnippet_api.js"
    mode: 0644
    owner: xsnippet
    group: xsnippet
- copy:
    src: nginx.conf
    dest: "/home/xsnippet/"

- name: prepare the pod config
  template:
    src: xsnippet.yml.j2
    dest: "/home/xsnippet/xsnippet.yml"
    mode: 0600
    owner: xsnippet
    group: xsnippet

- name: check if pod-xsnippet.service exists
  stat:
    path: "/home/xsnippet/.config/systemd/user/pod-xsnippet.service"
  register: xsnippet_service
- set_fact:
    xsnippet_service_exists: "{{ xsnippet_service.stat.isreg is defined and xsnippet_service.stat.isreg }}"

- name: stop xsnippet
  systemd:
    name: pod-xsnippet
    enabled: no
    state: stopped
    scope: user
  when: xsnippet_service_exists

- name: ensure there is no xsnippet pod
  command: "podman pod rm --force --ignore xsnippet"
  args:
    chdir: "/home/xsnippet"

- name: (re-)create the xsnippet pod
  command: "podman play kube --start=false --log-driver=journald xsnippet.yml"
  args:
    chdir: "/home/xsnippet"

- name: generate systemd units
  command: "podman generate systemd --files --name xsnippet"
  args:
    chdir: "/home/xsnippet/.config/systemd/user"

- name: start xsnippet
  systemd:
    name: pod-xsnippet
    enabled: yes
    state: restarted
    scope: user

- name: proxy HTTP and HTTPS from host to containers
  include_role:
    name: sockets
    apply:
      become: yes
      become_user: root

- name: systemd unit - restart {{ restart_service_name }} on SSL renewal
  vars:
    restart_service_name: container-xsnippet-web.service
    watch_path: "/home/xsnippet/.config/letsencrypt/live/{{ xsnippet_api_server_name }}"
  template:
    src: "{{ item }}"
    dest: "/home/xsnippet/.config/systemd/user/xsnippet-api-{{ item | splitext | first }}"
    mode: 0600
    owner: xsnippet
    group: xsnippet
  loop:
    - cert-watcher.service.j2
    - cert-watcher.path.j2
  when: xsnippet_api_https_enabled

- name: systemd unit - restart {{ restart_service_name }} on SSL renewal
  vars:
    restart_service_name: container-xsnippet-web.service
    watch_path: "/home/xsnippet/.config/letsencrypt/live/{{ xsnippet_spa_server_name }}"
  template:
    src: "{{ item }}"
    dest: "/home/xsnippet/.config/systemd/user/xsnippet-web-{{ item | splitext | first }}"
    mode: 0600
    owner: xsnippet
    group: xsnippet
  loop:
    - cert-watcher.service.j2
    - cert-watcher.path.j2
  when: xsnippet_spa_https_enabled

- name: watch for SSL renewal and restart xsnippet-api if detected
  systemd:
    name: xsnippet-api-cert-watcher.path
    enabled: yes
    state: restarted
    scope: user
  when: xsnippet_api_https_enabled

- name: watch for SSL renewal and restart xsnippet-web if detected
  systemd:
    name: xsnippet-web-cert-watcher.path
    enabled: yes
    state: restarted
    scope: user
  when: xsnippet_spa_https_enabled
