# software versions
xsnippet_api_image: xsnippet/xsnippet-api:latest
xsnippet_db_image: docker.io/library/postgres:13
xsnippet_web_image: docker.io/library/nginx:stable
xsnippet_web_assets: https://github.com/xsnippet/xsnippet-web/releases/download/v1.1.5/xsnippet-web-v1.1.5.tar.gz

# xsnippet-db configuration
xsnippet_db_name: xsnippet
xsnippet_db_user: xsnippet
xsnippet_db_password: xsnippet
xsnippet_db_port: 5432
xsnippet_db_external_volume: ""

# application configuration
xsnippet_syntaxes: "{{ lookup('file', 'syntaxes.txt').split('\n') }}"
xsnippet_database_url: "postgresql://{{ xsnippet_db_user }}:{{ xsnippet_db_password }}@127.0.0.1:{{ xsnippet_db_port}}/{{ xsnippet_db_name }}"

# reverse-proxy configuration
xsnippet_api_server_name: api.xsnippet.org
xsnippet_spa_server_name: xsnippet.org

# SSL/TLS configuration
xsnippet_api_https_redirect: true
xsnippet_api_https_enabled: true
xsnippet_spa_https_redirect: true
xsnippet_spa_https_enabled: true

# Digitalocean token that can be used by certbot to generate SSL.
xsnippet_digitalocean_token: "{{ lookup('env', 'DIGITALOCEAN_TOKEN') | default('', True) }}"
