- name: update apt cache (if needed)
  apt: update_cache=yes cache_valid_time=3600

- name: install the nftables package
  apt:
    name:
      - nftables
    state: latest

- name: configure nftables
  copy:
    src: nftables.conf
    dest: /etc/nftables.conf
    mode: '0644'
    owner: root
    group: root
  notify:
    - Restart nftables

- name: enable and start nftables
  systemd:
    name: nftables
    state: started
    enabled: yes
