- name: update apt cache (if needed)
  apt: update_cache=yes cache_valid_time=3600

- name: install essential packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: latest

- name: add Podman gpg key
  apt_key:
    url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{ ansible_distribution_version }}/Release.key"
    state: present

- name: add Podman packages repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /"
    state: present
  register: newrepo

- name: update apt cache (if needed)
  apt: update_cache=yes
  when: newrepo.changed

- name: install the latest Podman
  apt: name=podman state=latest

- name: check if cgroups v2 are enabled
  stat:
    path: /sys/fs/cgroup/cgroup.controllers
  register: cgroups
- set_fact:
    cgroupsv2: "{{ cgroups.stat.isreg is defined and cgroups.stat.isreg }}"

- name: update GRUB configuration to enable cgroups v2
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="(.*)"$'
    line: 'GRUB_CMDLINE_LINUX="\1 systemd.unified_cgroup_hierarchy=1"'
    backrefs: yes
    state: present
  when: not cgroupsv2
- command: update-grub
  when: not cgroupsv2 and require_cgroupsv2

- name: Reboot the machine to apply the GRUB config changes
  reboot:
  when: not cgroupsv2 and require_cgroupsv2
