name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pre-commit

      - name: Run pre-commit
        run: |
          python -m pre_commit run --all-files --show-diff-on-failure

  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade ansible

      - name: Remove pre-baked PostgreSQL
        run:
          # Existing pre-baked PostgreSQL installation may conflict with the
          # PostgreSQL installed by our playbook. We better remove it for a
          # greater good.
          sudo apt purge 'postgresql-*'

      - name: Create block storage device (volume)
        run: |
          VOLUME_DEVICE="$(losetup -f)"
          VOLUME_IMAGE="${{ runner.temp }}/diskimage"

          dd if=/dev/zero of=$VOLUME_IMAGE bs=1M count=1024
          sudo losetup $VOLUME_DEVICE $VOLUME_IMAGE

          echo ::set-output name=uri::$VOLUME_DEVICE
        id: volume-device

      - name: Run the playbook
        run: |
          ansible-playbook \
            -vvv \
            -e volume_device="${{ steps.volume-device.outputs.uri }}" \
            --inventory inventories/ci \
            site.yml

      - name: Smoke test
        run: |
          for i in `seq 180`; do
            curl http://localhost/v1/syntaxes && exit 0 || sleep 1
          done

          echo "http://localhost/v1/syntaxes is unavailable after 180s. Giving up."
          exit 1
