name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade ansible

      - name: Run the all-in-one playbook
        run: |
          ansible-playbook -vv --inventory "xsnippet," --connection=local ansible/all-in-one/deploy.yaml

      - name: Smoke test
        run: |
          for i in `seq 180`; do
            curl http://localhost/v1/syntaxes && exit 0 || sleep 1
          done

          echo "http://localhost/v1/syntaxes is unavailable after 180s. Giving up."
          exit 1
